"""Detection signals for Provenance Guard.

Milestone 3 implements Signal 1 (LLM classification via Groq). Signal 2
(stylometric) and the two-signal confidence combination arrive in Milestone 4.
"""

import json
import os

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

# Verdict thresholds on a 0-1 AI-likelihood score (see planning.md section 2).
# score < HUMAN_MAX -> likely human; >= AI_MIN -> likely AI; between -> uncertain.
HUMAN_MAX = 0.40
AI_MIN = 0.70

# The LLM is non-deterministic and overconfident at the extremes, so we never
# let a single signal express absolute certainty.
SCORE_FLOOR = 0.05
SCORE_CEIL = 0.95

_SYSTEM_PROMPT = (
    "You are a forensic linguistics classifier that estimates whether a passage "
    "of text was written by a human or generated by an AI language model. "
    "You respond ONLY with a single JSON object and no other text."
)

_USER_PROMPT = (
    "Assess whether the following text was written by a human or generated by an "
    "AI language model. Return a JSON object with exactly two keys:\n"
    '  "ai_probability": a number from 0 to 1 (1 = almost certainly AI-generated, '
    "0 = almost certainly human-written),\n"
    '  "rationale": one or two sentences describing the main evidence.\n\n'
    'Text:\n"""\n{text}\n"""'
)

_client = None


def _get_client():
    """Lazily construct the Groq client so importing this module never fails."""
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set (add it to your .env file).")
        _client = Groq(api_key=api_key)
    return _client


def _clamp(value, low, high):
    return max(low, min(high, value))


def detect_llm(text):
    """Signal 1: ask Groq to assess human vs. AI authorship.

    Returns a dict: {"llm_score": float in [0.05, 0.95], "rationale": str}.
    Raises RuntimeError if the Groq call or response parsing fails, so the
    caller (the endpoint) can turn it into a 502.
    """
    client = _get_client()
    try:
        completion = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_PROMPT.format(text=text)},
            ],
        )
    except Exception as exc:  # network / auth / rate-limit errors from Groq
        raise RuntimeError(f"Groq request failed: {exc}") from exc

    content = completion.choices[0].message.content
    try:
        data = json.loads(content)
        raw_score = float(data["ai_probability"])
        rationale = str(data.get("rationale", "")).strip()
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise RuntimeError(f"Could not parse Groq response: {content!r}") from exc

    return {
        "llm_score": round(_clamp(raw_score, SCORE_FLOOR, SCORE_CEIL), 4),
        "rationale": rationale,
    }


def attribution_for(score):
    """Map a 0-1 AI-likelihood score to a verdict label."""
    if score >= AI_MIN:
        return "likely_ai"
    if score < HUMAN_MAX:
        return "likely_human"
    return "uncertain"


if __name__ == "__main__":
    # Independent test harness: `python detection.py`
    from dotenv import load_dotenv

    load_dotenv()

    samples = {
        "human-personal": (
            "Honestly? I burnt the toast again. Third time this week. My kitchen "
            "smells like a campfire and the smoke alarm has opinions about my life "
            "choices at 7am."
        ),
        "ai-generic": (
            "Effective time management is essential for achieving personal and "
            "professional goals. By prioritizing tasks, setting clear objectives, "
            "and minimizing distractions, individuals can significantly improve "
            "their productivity and overall well-being."
        ),
    }
    for name, sample in samples.items():
        result = detect_llm(sample)
        print(
            f"{name:16s} llm_score={result['llm_score']:.2f} "
            f"attribution={attribution_for(result['llm_score'])}\n"
            f"    rationale: {result['rationale']}\n"
        )
